### ISSUE TITLE
write_dynamical_signature error

### ISSUE THREAD

**Issue by jiali0411** [gregorpatof/nrgten_package#1]
Hi, I am trying to get the dynamic signature from a PDB file as you have in the documentation. I used the same scripts in your documentation and with your test file:
```python
if __name__ == "__main__":
	model = ENCoM("test_medium.pdb")
	model.write_dynamical_signature("signature.txt")
```
When I run the script, I got this error:
```txt
Traceback (most recent call last):
  File "rmsip_example.copy.py", line 10, in <module>
    insulin_nmr.write_dynamical_signature("signature.txt")
  File "/envs/mypython3/lib/python3.8/site-packages/nrgten/enm.py", line 593, in write_dynamical_signature
    assert len(masses) == len(bfacts)
TypeError: object of type 'NoneType' has no len()
```
I tried every pdf file in your example folder but they all get the same error. 

I also tried the `compute_bfacts()` function, here my script:
```python
if __name__ == "__main__":
	model = ENCoM("2lwz.pdb")
	dyna_sig = model.compute_bfacts()
	print(dyna_sig)
```
And I got an error: 
```txt
Traceback (most recent call last):
  File "nrgten_dynamics.py", line 12, in <module>
    dyna_sig = model.compute_bfacts()
AttributeError: 'ENCoM' object has no attribute 'compute_bfacts'
```
Seems like `compute_bfacts()` didn't work. Would you help me to fix it? 

Thank you!

**Comment by gregorpatof** [comment]
Hi!

Sorry about that, I made some changes and need to update the documentation.
The reason you are getting the error is that you need to compute the
bfactors before trying to access the dynamical signature. The method is now
called compute_bfactors() instead of compute_bfacts(). Try it like this:

model = ENCoM("test_medium.pdb")
model.compute_bfactors()
model.write_dynamical_signature("signature.txt")

Cheers,
Olivier

**Comment by jiali0411** [comment]
Thank you! It worked with function `compute_bfactors()`

Thanks,
Jiali
