### ISSUE TITLE
program not properly installed

### ISSUE THREAD

**Issue by Rojo14** [gregorpatof/nrgten_package#3]
Hello, 

I have this error when using making sure the program is installed on my system. I wondered what the issue is 

raise ValueError("NRGTEN seems installed on your system, but does not give the proper value for this test...")
ValueError: NRGTEN seems installed on your system, but does not give the proper value for this test...

**Comment by gregorpatof** [comment]
Hi,

Sorry about that, I forgot to update the test value when some updates led to a tiny nonsignificant change. If you do a pull on nrgten_examples you should get the expected success message now.

**Comment by Rojo14** [comment]
Hello, 

I still have the same error message, I am not sure what can be the issue

**Comment by gregorpatof** [comment]
And you have executed:
git pull
inside the nrgten_examples directory?

**Comment by Rojo14** [comment]
Yes I did, it says that it is successfully updated

**Comment by gregorpatof** [comment]
Alright, can you pull again and paste the output you get here? It will now show the expected and computed value. My guess is the difference will be quite small, and if it is you can just ignore the issue and use the package as intended. It is probably due to discrepancies in your NumPy version or system architecture leading to floating-point errors accumulating the the entropy computation.

**Comment by gregorpatof** [comment]
Ok yeah, you can ignore it. Sorry again about that, I will change the tolerance for the test to diff < 0.01.

**Comment by Rojo14** [comment]
Great! Thank you very much for your help!
